name: washihaji
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ten-thousand.png
    - assets/images/five-thousand.png
    - assets/images/thousand.png
    - assets/images/five-hundred.png
    - assets/images/hundred.png
    - assets/images/fifty.png
    - assets/images/ten.png
    - assets/images/five.png
    - assets/images/one.png
